print('------------------------------------------------------')
print('                "Hello.py"')
print('------------------------------------------------------')
nombre = input('What is your name?: ')
print(f'Hola, {nombre} !')
